# Generated by Django 5.2.3 on 2025-07-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
