# Generated by Django 5.2.3 on 2025-07-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_cryptocurrency_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='gradual_update_end',
            field=models.DateTimeField(blank=True, help_text='When gradual update ends', null=True),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='gradual_update_start',
            field=models.DateTimeField(blank=True, help_text='When gradual update starts', null=True),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='If set, price will gradually adjust to this target.', max_digits=20, null=True),
        ),
    ]
