# Generated by Django 5.2.3 on 2025-07-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_cryptocurrency_gradual_update_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='gradual_update_end',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='gradual_update_start',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='target_price',
        ),
    ]
