# Generated by Django 5.2.3 on 2025-07-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0002_deposit_price_at_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='price_at_deposit',
        ),
        migrations.AddField(
            model_name='deposit',
            name='coin_quantity',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
