# Generated by Django 5.2.3 on 2025-07-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0003_remove_deposit_price_at_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='price_at_deposit',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='coin_quantity',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
