# Generated by Django 5.2.3 on 2025-07-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0006_alter_deposit_coin_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='coin_quantity',
        ),
    ]
