# Generated by Django 5.2.3 on 2025-07-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0007_remove_deposit_coin_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='coin_quantity',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
