# Generated by Django 5.2.3 on 2025-07-10 11:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0008_deposit_coin_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='price_at_deposit',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='coin_quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20),
        ),
    ]
